# Run it with inventory:
# ansible-playbook demo/inventory/fetch-inventory.yml -i <path>/.config/flightctl/flightctl.inventory.yaml
#
# With the setup as follows:
#
# File <path>/.config/flightctl/flightctl.inventory.yaml:
#  ---
#  plugin: flightctl.core.flightctl
#  flightctl_validate_certs: False
#  verify_ssl: False
#  additional_groups:
#    - name: group0
#      label_selectors:
#        - fleet = 'fleet-00'
#      field_selectors:
#        - metadata.name = 'device-03'
#        - metadata.name in ('device-03', 'device-01')
#    - name: group6
#      field_selectors:
#        - metadata.owner = "Fleet/fleet-06"
#  request_timeout: 120
#  flightctl_config_file: <path>/.config/flightctl/client.yaml
#
#  Note: The above example of `flightctl.inventory.yaml` it uses `flightctl_config_file` to read values from it.
#         Those values may be overridden in the `flightctl.inventory.yaml` file itself.
#
#
# File: <path>/.config/flightctl/client.yaml
# ---
# authentication: {}
# service:
#   insecureSkipVerify: true
#   server: https://api.10.50.15.28.nip.io:3443
#
#
# After running the prepare-devices-and-fleets.yml playbook, expected result:
#
#   {
#     "all_devices": [
#       "device-ansible-example",
#       "device-ansible-example-2",
#       "device-01",
#       "device-02",
#       "device-ansible-example-3",
#       "device-03"
#     ],
#     "fleet_06_devices": [
#       "device-01",
#       "device-02"
#     ],
#     "fleet_ansible_example_devices": [
#       "device-ansible-example-3"
#     ],
#     "group0_devices": [
#       "device-03"
#     ],
#     "group6_devices": [
#       "device-01",
#       "device-02"
#     ],
#     "ungrouped_devices": [
#       "device-ansible-example",
#       "device-ansible-example-2"
#     ]
#     }
#   }
#
#

- name: Test Flight Control Collection with Dynamic Inventory plugin
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Display devices from the inventory
      debug:
        msg:
          all_devices: "{{ groups.all }}"
          ungrouped_devices: "{{ groups.ungrouped }}"
          fleet_06_devices: "{{ groups.fleet_06 }}"
          fleet_ansible_example_devices: "{{ groups.fleet_ansible_example }}"
          group0_devices: "{{ groups.group0 }}"
          group6_devices: "{{ groups.group6 }}"
