- name: Test Flight Control Collection to create resources
  hosts: localhost
  gather_facts: false

  # TODO verify demos work with new response types
  tasks:
    - name: Set default credentials
      ansible.builtin.set_fact:
        credential_defaults: &credential_defaults
          flightctl_config_file: "{{ flightctl_config_file | default(omit) }}"
          flightctl_ca_path: "{{ flightctl_ca_path | default(omit)}}"
          flightctl_token: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJsVVFsb1BHaWxWV0RQNUNsem5BbGRtSFhxQWo3MXhJcTdtaFVkNUtOdnlFIn0.eyJleHAiOjE3NDM1MzkwMTcsImlhdCI6MTc0MzUzMjQxNywianRpIjoiNGE1NjI4MTQtNTVkOS00M2FjLWI0ODAtNDI5Mjg2ZGE2NGQzIiwiaXNzIjoiaHR0cDovL2F1dGguMTAwLjExMC42Ny4xNDAubmlwLmlvOjgwODEvcmVhbG1zL2ZsaWdodGN0bCIsInN1YiI6ImRlbW91c2VyIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiZmxpZ2h0Y3RsIiwic2lkIjoiYTdmNDgzNDQtY2Q1Ny00OGZjLTk0NzktYjBhMjljMjBjMWRlIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwOi8vbG9jYWxob3N0OjkwMDAiXSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInByZWZlcnJlZF91c2VybmFtZSI6ImRlbW91c2VyIn0.RydvNBepBxcNxH1ETGh-pOznmwy9OCKO3La1-ts-t0e56AiluxggNCW65oamO6tF_CQE1_B-iBs352L6t8j0Nz7LyYzdQpYIkrMSrZ0Rev5XJqlnomQShlOcazRk8CIfnQkJkpjcFAj-nKDRADPr0YX0yP6r6GwdhFwLhLF47E3VgRUPHXjP1FXN6UquW1lOjaS-ZtgMuae71KhHUavHhEzCr8FZzwQrvnc_tu1G2pcUEVtrArxLSgzbXPmtmC55QNCEjLZzKCC_CcvjglhrigXo5-wbVA3zSNU8oFZcY7g4sl_KhjWtJhGc2-0WAVCSMNBZjjGYPEstBUp3XsLgGQ"
          flightctl_host: "https://api.100.110.67.140.nip.io:3443"
          flightctl_validate_certs: "{{ flightctl_validate_certs | default(False)}}"

    - name: Get all devices
      flightctl.core.flightctl_resource_info:
        <<: *credential_defaults
        kind: Device

    - name: Get all fleets
      flightctl.core.flightctl_resource_info:
        <<: *credential_defaults
        kind: Fleet

    - name: Get information about a specific device
      flightctl.core.flightctl_resource_info:
        <<: *credential_defaults
        kind: Device
        name: "2bd0rgpir74c5jtrhfb1idvb2cvvvinem24t727qdudfcqr60sog"
      register: result

    - name: Get information about a specific device
      flightctl.core.flightctl_resource_info:
        <<: *credential_defaults
        kind: Device
        label_selector: "owner=mparra"

    - name: Create a test device in check_mode
      flightctl.core.flightctl_resource:
        <<: *credential_defaults
        kind: Device
        name: "device-ansible-example"
        resource_definition:
          apiVersion: flightctl.io/v1alpha1
          kind: Device
          metadata:
            name: "device-ansible-example"
            labels:
              fleet: default
              novalue: ""
      check_mode: true

    - name: Create a test device
      flightctl.core.flightctl_resource:
        <<: *credential_defaults
        kind: Device
        name: "device-ansible-example"
        resource_definition:
          apiVersion: flightctl.io/v1alpha1
          kind: Device
          metadata:
            name: "device-ansible-example"
            labels:
              fleet: default
              novalue: ""
      register: _result

    - name: Assert that Device was created
      ansible.builtin.assert:
        that:
          - _result.changed
          - _result is success

    - name: Create a test device again (idempotence)
      flightctl.core.flightctl_resource:
        <<: *credential_defaults
        kind: Device
        name: "device-ansible-example"
        resource_definition:
          apiVersion: flightctl.io/v1alpha1
          kind: Device
          metadata:
            name: "device-ansible-example"
            labels:
              fleet: default
              novalue: ""
      register: _result

    - name: Assert that Device was not created
      ansible.builtin.assert:
        that:
          - not _result.changed
          - _result is success

    - name: Create a new test device
      flightctl.core.flightctl_resource:
        <<: *credential_defaults
        kind: Device
        name: "device-ansible-example-2"
        api_version: flightctl.io/v1alpha1
      register: _result

    - name: Assert that Device was created
      ansible.builtin.assert:
        that:
          - _result.changed
          - _result is success

    - name: Update new test device
      flightctl.core.flightctl_resource:
        <<: *credential_defaults
        kind: Device
        name: "device-ansible-example-2"
        api_version: flightctl.io/v1alpha1
        resource_definition:
          apiVersion: flightctl.io/v1alpha1
          kind: Device
          metadata:
            labels:
              fleet: default
              novalue: ""
      register: _result

    - name: Assert that Device was updated
      ansible.builtin.assert:
        that:
          - _result.changed
          - _result is success

    - name: Get information about a specific device
      flightctl.core.flightctl_resource_info:
        <<: *credential_defaults
        kind: Device
        name: "device-ansible-example"

    - name: Delete a test device in check_mode
      flightctl.core.flightctl_resource:
        <<: *credential_defaults
        kind: Device
        name: "device-ansible-example"
        state: absent
      check_mode: true

    - name: Get information about a specific device
      flightctl.core.flightctl_resource_info:
        <<: *credential_defaults
        kind: Device
        name: "device-ansible-example"

    - name: Create a new fleet
      flightctl.core.flightctl_resource:
        <<: *credential_defaults
        kind: Fleet
        name: "fleet-ansible-example"
        resource_definition: "{{ lookup('file', 'fleet.yml') | from_yaml }}"
      register: _result

    - name: Assert that Fleet was created
      ansible.builtin.assert:
        that:
          - _result.changed
          - _result is success

    - name: Create a new device
      flightctl.core.flightctl_resource:
        <<: *credential_defaults
        kind: Device
        name: "device-ansible-example-3"
        resource_definition: "{{ lookup('file', 'device.yml') | from_yaml }}"
      register: _result

    - name: Assert that Device was created
      ansible.builtin.assert:
        that:
          - _result.changed
          - _result is success

    - name: Create a new repository
      flightctl.core.flightctl_resource:
        <<: *credential_defaults
        kind: Repository
        name: "repository-ansible-example"
        resource_definition:
          apiVersion: flightctl.io/v1alpha1
          kind: Repository
          metadata:
            name: repository-ansible-example
          spec:
            url: https://github.com/flightctl/flightctl.git
            type: git
      register: _result

    - name: Assert that Repository was created
      ansible.builtin.assert:
        that:
          - _result.changed
          - _result is success
