---
- name: Test Flight Control Collection to delete resources
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Set default credentials
      ansible.builtin.set_fact:
        credential_defaults: &credential_defaults
          flightctl_config_file: "{{ flightctl_config_file | default(omit) }}"
          flightctl_ca_path: "{{ flightctl_ca_path | default(omit) }}"
          flightctl_token: "{{ flightctl_token | default(omit) }}"
          flightctl_host: "{{ flightctl_host | default(omit) }}"
          flightctl_validate_certs: "{{ flightctl_validate_certs | default(True) }}"

    - name: Delete devices
      flightctl.core.flightctl:
        <<: *credential_defaults
        kind: Device
        name: "{{ item }}"
        state: absent
        flightctl_ca_path: "{{ flightctl_ca_path | default(omit) }}"
        flightctl_token: "{{ flightctl_token | default(omit) }}"
        flightctl_host: "{{ flightctl_host | default(omit) }}"
        flightctl_validate_certs: "{{ flightctl_validate_certs | default(True) }}"
      loop:
        - "device-ansible-example"
        - "device-ansible-example-2"
        - "device-ansible-example-3"

    - name: Delete fleet
      flightctl.core.flightctl:
        <<: *credential_defaults
        kind: Fleet
        name: "fleet-ansible-example"
        state: absent

        flightctl_ca_path: "{{ flightctl_ca_path | default(omit) }}"
        flightctl_token: "{{ flightctl_token | default(omit) }}"
        flightctl_host: "{{ flightctl_host | default(omit) }}"
        flightctl_validate_certs: "{{ flightctl_validate_certs | default(True) }}"
    - name: Delete repository
      flightctl.core.flightctl:
        <<: *credential_defaults
        kind: Repository
        name: "repository-ansible-example"
        state: absent
        flightctl_ca_path: "{{ flightctl_ca_path | default(omit) }}"
        flightctl_token: "{{ flightctl_token | default(omit) }}"
        flightctl_host: "{{ flightctl_host | default(omit) }}"
        flightctl_validate_certs: "{{ flightctl_validate_certs | default(True) }}"
