- name: Align resources from a git repo
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Set default credentials
      ansible.builtin.set_fact:
        credential_defaults: &credential_defaults
          flightctl_config_file: "{{ flightctl_config_file | default(omit) }}"
          flightctl_ca_path: "{{ flightctl_ca_path | default(omit)}}"
          flightctl_token: "{{ flightctl_token | default(omit)}}"
          flightctl_host: "{{ flightctl_host | default(omit)}}"
          flightctl_validate_certs: "{{ flightctl_validate_certs | default(True)}}"

    - name: Checkout repo
      ansible.builtin.git:
        repo: 'https://github.com/DakCrowder/gitops-demo.git'
        dest: /tmp/gitops-demo

    - name: Load fleet definition
      set_fact:
        fleet_definition: "{{ lookup('file', '/tmp/gitops-demo/fleet.yml') | from_yaml }}"

    - name: Create fleet from demo
      flightctl.core.flightctl:
        <<: *credential_defaults
        resource_definition: "{{ fleet_definition }}"
