---
name: Linters

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@24.12.2
